
version: 2

models:
  - name: cleaned_service_requests
    description: >
      The cleaned 311 service requests made by New Yorkers.
    config:
      materialized: table
      database: nyc_311
      schema: nyc_311_data
    columns:
      - name: unique_key
        description: The primary key for this table.
        data_tests:
          - not_null
          - unique
      - name: agency
        description: >
          The NYC agency that received a complaint from a New Yorker.
        data_tests:
          - not_null
          # - accepted_values:
          #     values:
          #       - ACS
          #       - DOT
          #       - NYPD

sources:
  - name: nyc_311_service_requests
    description: >
      This **dbt source** is a copy of the dataset 
      [311 Service Requests from 2010 to Present](https://data.cityofnewyork.us/Social-Services/311-Service-Requests-from-2010-to-Present/erm2-nwe9/about_data)
      hosted on [NYC OpenData portal](https://opendata.cityofnewyork.us/).
    database: nyc_311
    schema: nyc_311_data
    # database: raw
    # schema: nyc
    meta:
      contains_pii: false
      owner: "@giacomo"
    tags:
      - '311'
      - complaint
      - nyc
    tables:
      - name: service_requests
        description: >
          The raw 311 service requests made by New Yorkers.
        identifier: raw_data
        # identifier: service_requests
        loader: dlt
        loaded_at_field: ingested_at
        columns:
          - name: unique_key
            description: The primary key for this table.
            data_tests:
              - not_null
              - unique
