DATASET_FILE_PATH = "data/raw/311_service_requests.csv"
DATE_FORMAT = "%Y-%m-%d"
# NYC_311_SERVICE_REQUESTS_CSV_FILE_URL = "https://data.cityofnewyork.us/api/views/755u-8jsi/rows.csv?accessType=DOWNLOAD"
NYC_311_SERVICE_REQUESTS_CSV_FILE_URL = "https://data.cityofnewyork.us/api/views/erm2-nwe9/rows.csv?accessType=DOWNLOAD"
NYC_311_SERVICE_REQUESTS_TABLE = "service_requests"
NYC_TAXI_ZONES_FILE_PATH = "data/raw/taxi_zones.csv"
NYC_TAXI_ZONES_TABLE = "zones"
STATS_FILE_PATH = "data/outputs/service_requests_stats.json"

BROOKLYN_GEODATAFRAME_FILE_PATH = "data/staging/brooklyn.geojson"
MANHATTAN_GEODATAFRAME_FILE_PATH = "data/staging/manhattan.geojson"

BROOKLYN_MAP_FILE_PATH_HTML = "data/outputs/brooklyn_map.html"
FACET_PLOT_PATH_HTML = "data/outputs/facet_plot.html"
MANHATTAN_MAP_FILE_PATH_HTML = "data/outputs/manhattan_map.html"
